FROM mcr.microsoft.com/devcontainers/python:3.11-bookworm

ARG NPM_CONFIG_REGISTRY
ARG PIP_INDEX_URL
ARG RestoreSources

ENV NPM_CONFIG_REGISTRY="${NPM_CONFIG_REGISTRY:-https://registry.npmjs.org/}" \
    PIP_INDEX_URL="${PIP_INDEX_URL:-https://pypi.org/simple/}" \
    RestoreSources="${RestoreSources:-https://api.nuget.org/v3/index.json}"
